[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci --include=optional && (npm install -D --no-save --package-lock=false @rollup/rollup-linux-x64-gnu || true) && npm run build"
  base = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200