name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (React)
        - Smart Contracts
        - Documentation
        - Build/Deploy
        - Other
    validations:
      required: true

  - type: input
    id: network
    attributes:
      label: Network
      description: Which network were you using?
      placeholder: "e.g., Sepolia, Mainnet, Local"
    validations:
      required: false

  - type: input
    id: wallet
    attributes:
      label: Wallet
      description: Which wallet were you using?
      placeholder: "e.g., MetaMask, WalletConnect"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment information
      value: |
        - OS:
        - Browser:
        - Node Version:
        - Wallet Version:
      render: markdown
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output, error messages, or console output
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots
      placeholder: Any additional information that might help us understand the issue...
    validations:
      required: false